#!/bin/bash

pixel_path="$HOME/.config/bash_pixel_art/"

file_count=$(find $pixel_path -maxdepth 1 -type f | wc -l)

file_array=($(find $pixel_path -maxdepth 1 -type f))

random_index=$((RANDOM%file_count))
random_file="${file_array[$random_index]}"

"$random_file"



